import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { AuthGuard } from "@/features/user/authGuard";
import { ThemeProvider } from "./ThemeProvider";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <AuthGuard>
            <ThemeProvider attribute="class" defaultTheme="light">
                {children}
            </ThemeProvider>
          </AuthGuard>
        </body>
      </html>
    </StoreProvider>
  );
}
